### PR TITLE
MAD-X: Add TKICKER, HKICKER and VKICKER to accepted input

### PR DESCRIPTION
**Pull request by n01r**
We add HKICKER and VKICKER semantically as available elements of type KICKER.
We also add TKICKER and treat it exactly the same as KICKER.

Depends on #419, merge only after rebase

### CODE REVIEW

**Comment by ax3l** [comment]
@n01r ready for rebase :)

**Comment by n01r** [comment]
@ax3l Rebase completed :+1:

**Comment by n01r** [comment]
I took the freedom to combine the test for `KICKER` and `TKICKER` since we treat them exactly the same.

**Review by ax3l — APPROVED** [review]
Thank you, Marco! :)

**Review by cemitch99 — APPROVED** [review]
Looks good to me.

**Pull request merged**
