### PR TITLE
Rename sigma to lambda where not stddev

### PR DESCRIPTION
**Pull request by n01r**
This commit replaces (hopefully) all occurrences of `sigma<...>` as input to particle distributions with `lambda<...>` since the parameter describes the axis intercepts of the phase space ellipse and is only identical to the RMS extents when there is no correlation between q (position) and p (momentum).

This breaking change belongs to the same set of changes as #541.

### CODE REVIEW

**Comment by n01r** [comment]
This also solves the name duplication where in most of our examples there is an analysis script which calculates `sig<...>` values which actually describe beam moments and standard deviations. So I made no change to these files. But I hope I got everything else and did not change too much.

**Review by RTSandberg — APPROVED** [review]
That is a lot of sigmas to change to lambdas!  It looks good to me

**Review by ax3l — APPROVED** [review]
Thank you, @n01r !

Waiting for @cemitch99 to confirm and then we synchronize the merge with #541

**Review by cemitch99 — APPROVED** [review]
This looks good to me.

**Comment by ax3l** [comment]
@n01r can you please rebase / merge development? :)

**Comment by n01r** [comment]
Rebased :)

**Review by ax3l — APPROVED** [review]
Thank you! :)

**Pull request merged**
