### PR TITLE
Charge Deposition: Fix Sign

### PR DESCRIPTION
**Pull request by ax3l**
This fixes the charge deposition. Electrons should deposit negative charge :-)

### CODE REVIEW

**Review by cemitch99 — APPROVED** [review]
Great!

**Review by RemiLehe — APPROVED** [review]

**Comment by RemiLehe** [comment]
@ax3l It seems that you will need to modify the test to replace:
```
assert math.isclose(beam_charge, 1.0e-9)
``` 
with 
```
assert math.isclose(beam_charge, -1.0e-9)
```

**Comment by ax3l** [comment]
correct, wanted to quickly see if this fails now as intended.

It does, but I also need to increase the tolerance a little now: `beam_charge=-1.0000000087381137e-09`

**Comment by cemitch99** [comment]
> @ax3l It seems that you will need to modify the test to replace:
> 
> ```
> assert math.isclose(beam_charge, 1.0e-9)
> ```
> 
> with
> 
> ```
> assert math.isclose(beam_charge, -1.0e-9)
> ```

This is a good point.  In Impact-Z, the sign problem is avoided by treating all charges as positive.  (So electrons are treated as positrons.) This makes life a bit easier, and it does not affect tracking in the external fields because the field strength is given in a normalized form (scaled by signed magnetic rigidity p/q).  Either option is fine, as long as the sign of the pushed single-particle charge is the same as the sign of the deposited charge of the bunch.

**Comment by ax3l** [comment]
I like that we have both, would allow us to do some (short beamline) tests with partly neutral beams as come out from some plasma sources.

**Pull request merged**
