### PR TITLE
Add Python CSR wake plotting test.

### PR DESCRIPTION
**Pull request by cemitch99**
This adds a Python plotting script for the CSR wakefield in tests/python, as a follow-up to [PR#627](url).  The original author is `xbojanic`.

### CODE REVIEW

**Review by cemitch99 — COMMENTED** [review]
Locally, this gives me:

NO mpi4py load
Segmentation fault: 11

even if I comment lines 141-144.

**Comment by ax3l** [comment]
Can you try if the standalone run of the test via `pytest` works locally?
https://github.com/AMReX-Codes/pyamrex?tab=readme-ov-file#test

**Review by ax3l — APPROVED** [review]

**Comment by cemitch99** [comment]
Yes, this test passes if I run it locally via pytest, as expected.  The saved png files may be deleted on completion--is there a way to run via pytest and also view the generated png files?

**Comment by ax3l** [comment]
Good question. I have to google that for pytest.

**Pull request merged**
