### PR TITLE
Add helper function for Python Twiss input

### LINKED ISSUE #680: Python Distributions: By Twiss
We already support generalized coordiante + twiss input in inputs files for beam distributions #527:
https://impactx.readthedocs.io/en/latest/usage/parameters.html#initial-beam-distributions

but not yet in Python:
https://impactx.readthedocs.io/en/latest/usage/python.html#initial-beam-distributions

We could either change the defaults to take twiss parameters or add a tiny helper function that takes generalized coordinates and returns twiss equivalents, which we pass in the constructors:
https://impactx.readthedocs.io/en/latest/theory/beam_distribution.html
```py
#   particle bunch
distr = distribution.Waterbag(
    lambdaX=3.9984884770e-5,
    lambdaY=3.9984884770e-5,
    lambdaT=1.0e-3,
    lambdaPx=2.6623538760e-5,
    lambdaPy=2.6623538760e-5,
    lambdaPt=2.0e-3,
    muxpx=-0.846574929020762,
    muypy=0.846574929020762,
    mutpt=0.0,
)
```
```py
#   particle bunch
distr = distribution.Waterbag(**twiss(
    betaX=2.82161941,
    betaY=2.82161941,
    alphaX=-1.59050035,
    alphaY=1.59050035,
    # ...
))
```

### PR DESCRIPTION
**Pull request by n01r**
Close #680

- [x] add helper function `twiss`
- [x] add FODO example run script
- [x] add CTest
- [x] add documentation

### CODE REVIEW

**Comment by n01r** [comment]
This will close #680

**Review by cemitch99 — APPROVED** [review]
This looks great.  (Note one test is failing due to the import on line 21 of __init__.py.)

**Comment by n01r** [comment]
Ah, seems like I may need to add `# noqa` after all.

**Comment by n01r** [comment]
The documentation preview does not seem to render the `.. autofunction:: impactx.twiss` yet. But here's what it looks like locally.
image

**Review by ax3l — APPROVED** [review]
Very nice, thank you for this! :sparkles:

**Comment by ax3l** [comment]
fyi @moellep

**Pull request merged**
